/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.108
 * Generated at: 2025-08-23 16:41:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.db.DBConnect;
import java.sql.Connection;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/component/footer.jsp", Long.valueOf(1755533899363L));
    _jspx_dependants.put("/component/navbar.jsp", Long.valueOf(1755622599510L));
    _jspx_dependants.put("/component/css.jsp", Long.valueOf(1753599776025L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("com.db.DBConnect");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Hospital Management System</title>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.0/css/all.min.css\"\r\n");
      out.write("	integrity=\"sha512-DxV+EoADOkOygM4IR9yXP8Sb2qwgidEmeqAEmDKIOfPRQZOWbXCzLC6vjbZyy0vPisbH2SyW27+ddLVCN+OMzQ==\"\r\n");
      out.write("	crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("		integrity=\"sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM\"\r\n");
      out.write("		crossorigin=\"anonymous\"></script>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("/* Smooth scrolling for anchor links */\r\n");
      out.write("html {\r\n");
      out.write("    scroll-behavior: smooth;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Card Styles */\r\n");
      out.write(".paint-card {\r\n");
      out.write("    box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);\r\n");
      out.write("    border-radius: 12px;\r\n");
      out.write("    transition: all 0.3s ease-in-out;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write(".paint-card:hover {\r\n");
      out.write("    transform: translateY(-5px);\r\n");
      out.write("    box-shadow: 0 8px 25px rgba(0, 0, 0, 0.3);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Image Hover */\r\n");
      out.write("#dc {\r\n");
      out.write("    border-radius: 12px;\r\n");
      out.write("    transition: all 0.4s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write("#dc:hover {\r\n");
      out.write("    transform: scale(1.05);\r\n");
      out.write("    box-shadow: 0 8px 25px rgba(0, 0, 0, 0.4);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Team Images */\r\n");
      out.write(".team-img {\r\n");
      out.write("    border-radius: 12px;\r\n");
      out.write("    object-fit: cover;\r\n");
      out.write("    height: 300px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Section Headings */\r\n");
      out.write(".section-title {\r\n");
      out.write("    font-size: 2rem;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    margin-bottom: 1.5rem;\r\n");
      out.write("    color: #2C3E50;\r\n");
      out.write("    text-transform: uppercase;\r\n");
      out.write("    letter-spacing: 1px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Carousel Overlay Text */\r\n");
      out.write(".carousel-item {\r\n");
      out.write("    position: relative;\r\n");
      out.write("}\r\n");
      out.write(".carousel-item .overlay-text {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 50%;\r\n");
      out.write("    left: 50%;\r\n");
      out.write("    transform: translate(-50%, -50%);\r\n");
      out.write("    color: white;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    background: rgba(0, 0, 0, 0.4);\r\n");
      out.write("    padding: 20px 30px;\r\n");
      out.write("    border-radius: 10px;\r\n");
      out.write("}\r\n");
      out.write(".carousel-item .overlay-text h1 {\r\n");
      out.write("    font-size: 3rem;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    margin-bottom: 15px;\r\n");
      out.write("}\r\n");
      out.write(".carousel-item .overlay-text p {\r\n");
      out.write("    font-size: 1.2rem;\r\n");
      out.write("    margin-bottom: 15px;\r\n");
      out.write("}\r\n");
      out.write(".carousel-item .overlay-text .btn {\r\n");
      out.write("    font-size: 1rem;\r\n");
      out.write("    padding: 10px 20px;\r\n");
      out.write("}\r\n");
      out.write(".btn-learnmore {\r\n");
      out.write("    background-color: #2C3E50;  /* dark blue */\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    border: none;\r\n");
      out.write("    padding: 10px 20px;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    border-radius: 8px;\r\n");
      out.write("    transition: all 0.3s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write(".btn-learnmore:hover {\r\n");
      out.write("    background-color: #1ABC9C;  /* teal hover */\r\n");
      out.write("    transform: scale(1.05);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("/* Navbar background */\r\n");
      out.write(".navbar-custom {\r\n");
      out.write("    background: linear-gradient(90deg, #2C3E50, #34495E);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Nav links */\r\n");
      out.write(".navbar-nav .nav-link {\r\n");
      out.write("    color: white !important;\r\n");
      out.write("    font-weight: 500;\r\n");
      out.write("    margin-right: 14px;\r\n");
      out.write("    transition: 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write(".navbar-nav .nav-link:hover {\r\n");
      out.write("    color: #f39c12 !important; /* Gold hover */\r\n");
      out.write("    transform: translateY(-2px);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Custom dropdown button */\r\n");
      out.write(".custom-btn {\r\n");
      out.write("    background-color: #f39c12; /* Gold */\r\n");
      out.write("    color: white;\r\n");
      out.write("    border: none;\r\n");
      out.write("    border-radius: 8px;\r\n");
      out.write("    padding: 6px 14px;\r\n");
      out.write("    transition: 0.3s;\r\n");
      out.write("}\r\n");
      out.write(".custom-btn:hover {\r\n");
      out.write("    background-color: #d68910;\r\n");
      out.write("    transform: scale(1.05);\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark navbar-custom shadow-sm\">\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- Brand -->\r\n");
      out.write("    <a class=\"navbar-brand fw-bold\" href=\"index.jsp\">\r\n");
      out.write("      <i class=\"fa-solid fa-house-medical\"></i> MEDI HOME\r\n");
      out.write("    </a>\r\n");
      out.write("\r\n");
      out.write("    <!-- Mobile Toggler -->\r\n");
      out.write("    <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" \r\n");
      out.write("            data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" \r\n");
      out.write("            aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("      <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("    </button>\r\n");
      out.write("\r\n");
      out.write("    <!-- Navbar Links -->\r\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("      <ul class=\"navbar-nav ms-auto mb-2 mb-lg-0\">\r\n");
      out.write("\r\n");
      out.write("        ");
 
           Object userObj = session.getAttribute("userObj");
           if (userObj == null) { 
        
      out.write("\r\n");
      out.write("            <!-- Not logged in -->\r\n");
      out.write("            <li class=\"nav-item\"><a class=\"nav-link\" href=\"admin_login.jsp\"><i class=\"fa-solid fa-user-shield\"></i> Admin</a></li>\r\n");
      out.write("            <li class=\"nav-item\"><a class=\"nav-link\" href=\"doctor_login.jsp\"><i class=\"fa-solid fa-stethoscope\"></i> Doctor</a></li>\r\n");
      out.write("            <li class=\"nav-item\"><a class=\"nav-link\" href=\"user_appointment.jsp\"><i class=\"fa-solid fa-calendar-check\"></i> Appointment</a></li>\r\n");
      out.write("            <li class=\"nav-item\"><a class=\"nav-link\" href=\"user_login.jsp\"><i class=\"fa-solid fa-user\"></i> User</a></li>\r\n");
      out.write("\r\n");
      out.write("        ");
 
           } else { 
        
      out.write("\r\n");
      out.write("            <!-- Logged in user -->\r\n");
      out.write("            <li class=\"nav-item\"><a class=\"nav-link\" href=\"user_appointment.jsp\"><i class=\"fa-solid fa-calendar-check\"></i> Appointment</a></li>\r\n");
      out.write("            <li class=\"nav-item\"><a class=\"nav-link\" href=\"view_appointment.jsp\"><i class=\"fa-solid fa-eye\"></i> View Appointment</a></li>\r\n");
      out.write("\r\n");
      out.write("            <!-- User dropdown -->\r\n");
      out.write("            <div class=\"dropdown\">\r\n");
      out.write("              <button class=\"btn custom-btn dropdown-toggle\" type=\"button\" \r\n");
      out.write("                      id=\"dropdownMenuButton1\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("                <i class=\"fas fa-user-circle\"></i> \r\n");
      out.write("                ");
      out.print( ((com.entity.User)userObj).getFullname() );
      out.write("\r\n");
      out.write("              </button>\r\n");
      out.write("              <ul class=\"dropdown-menu dropdown-menu-end shadow\">\r\n");
      out.write("                <li><a class=\"dropdown-item\" href=\"changepassword.jsp\"><i class=\"fa-solid fa-key\"></i> Change Password</a></li>\r\n");
      out.write("                <li><a class=\"dropdown-item\" href=\"userLogout\"><i class=\"fa-solid fa-right-from-bracket\"></i> Logout</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        ");
 
           } 
        
      out.write("\r\n");
      out.write("\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Hero Carousel -->\r\n");
      out.write("    <div id=\"carouselExampleIndicators\" class=\"carousel slide\" data-bs-ride=\"carousel\">\r\n");
      out.write("        <div class=\"carousel-indicators\">\r\n");
      out.write("            <button type=\"button\" data-bs-target=\"#carouselExampleIndicators\" data-bs-slide-to=\"0\" class=\"active\"></button>\r\n");
      out.write("            <button type=\"button\" data-bs-target=\"#carouselExampleIndicators\" data-bs-slide-to=\"1\"></button>\r\n");
      out.write("            <button type=\"button\" data-bs-target=\"#carouselExampleIndicators\" data-bs-slide-to=\"2\"></button>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"carousel-inner\">\r\n");
      out.write("            <div class=\"carousel-item active\">\r\n");
      out.write("                <img src=\"img/101.jpg\" class=\"d-block w-100\" alt=\"Hospital Surgery\" style=\"height: 100vh; object-fit: cover;\">\r\n");
      out.write("                <div class=\"overlay-text\">\r\n");
      out.write("                    <h1>Welcome to Our Hospital</h1>\r\n");
      out.write("                    <p>Providing the best healthcare services with expert doctors.</p>\r\n");
      out.write("                    <a href=\"#featuress\" class=\"btn btn-learnmore\">Learn More</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"carousel-item\">\r\n");
      out.write("                <img src=\"img/102.jpg\" class=\"d-block w-100\" alt=\"Hospital\" style=\"height: 100vh; object-fit: cover;\">\r\n");
      out.write("                <div class=\"overlay-text\">\r\n");
      out.write("                    <h1>Compassionate Care</h1>\r\n");
      out.write("                    <p>Your health and comfort are our top priorities.</p>\r\n");
      out.write("                    <a href=\"#features\" class=\"btn btn-learnmore\">Learn More</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"carousel-item\">\r\n");
      out.write("                <img src=\"img/103.jpg\" class=\"d-block w-100\" alt=\"Doctors\" style=\"height: 100vh; object-fit: cover;\">\r\n");
      out.write("                <div class=\"overlay-text\">\r\n");
      out.write("                    <h1>Expert Doctors</h1>\r\n");
      out.write("                    <p>Our team of professionals ensures the best treatment possible.</p>\r\n");
      out.write("                    <a href=\"#team\" class=\"btn btn-learnmore\">Learn More</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#carouselExampleIndicators\" data-bs-slide=\"prev\">\r\n");
      out.write("            <span class=\"carousel-control-prev-icon\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("        <button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#carouselExampleIndicators\" data-bs-slide=\"next\">\r\n");
      out.write("            <span class=\"carousel-control-next-icon\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Features Section -->\r\n");
      out.write("    <!-- ================= Key Features Section ================= -->\r\n");
      out.write("<section id=\"features\" class=\"py-5 bg-light\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"text-center mb-5\">\r\n");
      out.write("            <h2 class=\"fw-bold \"style=\"text:#2C3E50;\">Why Choose Us</h2>\r\n");
      out.write("            <p class=\"text-muted\">Providing the best healthcare services with expert doctors and modern facilities.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row g-4\">\r\n");
      out.write("            <!-- Card 1 -->\r\n");
      out.write("            <div class=\"col-md-4\">\r\n");
      out.write("                <div class=\"card shadow-lg border-0 h-100 text-center p-4\">\r\n");
      out.write("                    <i class=\"fas fa-user-md fa-3x text-primary mb-3\"></i>\r\n");
      out.write("                    <h5 class=\"fw-bold\">Expert Doctors</h5>\r\n");
      out.write("                    <p class=\"text-muted\">Our team of certified and experienced doctors is always ready to serve you.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Card 2 -->\r\n");
      out.write("            <div class=\"col-md-4\">\r\n");
      out.write("                <div class=\"card shadow-lg border-0 h-100 text-center p-4\">\r\n");
      out.write("                    <i class=\"fas fa-hospital fa-3x text-success mb-3\"></i>\r\n");
      out.write("                    <h5 class=\"fw-bold\">Modern Facilities</h5>\r\n");
      out.write("                    <p class=\"text-muted\">State-of-the-art equipment and infrastructure for world-class healthcare.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Card 3 -->\r\n");
      out.write("            <div class=\"col-md-4\">\r\n");
      out.write("                <div class=\"card shadow-lg border-0 h-100 text-center p-4\">\r\n");
      out.write("                    <i class=\"fas fa-ambulance fa-3x text-danger mb-3\"></i>\r\n");
      out.write("                    <h5 class=\"fw-bold\">24/7 Support</h5>\r\n");
      out.write("                    <p class=\"text-muted\">Emergency support and ambulance services available round the clock.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>\r\n");
      out.write("    <hr>\r\n");
      out.write("    <div class=\"container py-5\" id=\"featuress\">\r\n");
      out.write("            <h2 class=\"fw-bold text-center  \"style=\"text:#2C3E50;\">Key Features Of Our Hospital</h2>\r\n");
      out.write("      <br>  <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-8 col-sm-12 p-4\">\r\n");
      out.write("                <div class=\"row g-3\">\r\n");
      out.write("                    <div class=\"col-md-6\">\r\n");
      out.write("                        <div class=\"card paint-card\">\r\n");
      out.write("                            <div class=\"card-body\">\r\n");
      out.write("                                <h5 class=\"fw-bold\">Clean Environment</h5>\r\n");
      out.write("                                <p>We maintain strict cleanliness protocols to provide a safe and hygienic environment for patients and staff.</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-6\">\r\n");
      out.write("                        <div class=\"card paint-card\">\r\n");
      out.write("                            <div class=\"card-body\">\r\n");
      out.write("                                <h5 class=\"fw-bold\">Safety First</h5>\r\n");
      out.write("                                <p>Advanced safety standards are followed to ensure risk-free healthcare services for everyone.</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-6\">\r\n");
      out.write("                        <div class=\"card paint-card\">\r\n");
      out.write("                            <div class=\"card-body\">\r\n");
      out.write("                                <h5 class=\"fw-bold\">Friendly Doctors</h5>\r\n");
      out.write("                                <p>Our doctors are approachable, kind, and always ready to provide patient-centered care.</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-6\">\r\n");
      out.write("                        <div class=\"card paint-card\">\r\n");
      out.write("                            <div class=\"card-body\">\r\n");
      out.write("                                <h5 class=\"fw-bold\">Medical Research</h5>\r\n");
      out.write("                                <p>We promote medical research and innovation to enhance treatments and healthcare outcomes.</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Right Image -->\r\n");
      out.write("            <div class=\"col-md-4 col-sm-12 d-flex align-items-center justify-content-center\">\r\n");
      out.write("                <img src=\"img/hos3.jpg\" class=\"img-fluid\" id=\"dc\" alt=\"Hospital\">\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <hr>\r\n");
      out.write("\r\n");
      out.write("    <!-- Team Section -->\r\n");
      out.write("    <div class=\"container py-5\" id=\"team\">\r\n");
      out.write("<div class=\"text-center mb-5\">\r\n");
      out.write("            <h2 class=\"fw-bold \"style=\"text:#2C3E50;\">Meet Our Doctors</h2>\r\n");
      out.write("            <p class=\"text-muted\">Our experienced medical specialists are here to care for you.</p>\r\n");
      out.write("        </div>        <div class=\"row g-4\">\r\n");
      out.write("            <div class=\"col-md-3 col-sm-6\">\r\n");
      out.write("                <div class=\"card paint-card text-center p-2\">\r\n");
      out.write("                    <img src=\"img/doctor4.jpg\" class=\"team-img\" width=\"100%\">\r\n");
      out.write("                    <h5 class=\"fw-bold mt-2\">Abhishek Pathak</h5>\r\n");
      out.write("                    <p class=\"text-muted\">(CEO & Chairman)</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-3 col-sm-6\">\r\n");
      out.write("                <div class=\"card paint-card text-center p-2\">\r\n");
      out.write("                    <img src=\"img/doctor5.jpg\" class=\"team-img\" width=\"100%\">\r\n");
      out.write("                    <h5 class=\"fw-bold mt-2\">Dr. Amruta Singh</h5>\r\n");
      out.write("                    <p class=\"text-muted\">(Chief Doctor)</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-3 col-sm-6\">\r\n");
      out.write("                <div class=\"card paint-card text-center p-2\">\r\n");
      out.write("                    <img src=\"img/doctor3.jpg\" class=\"team-img\" width=\"100%\">\r\n");
      out.write("                    <h5 class=\"fw-bold mt-2\">Dr. Aniket Kamble (MJ)</h5>\r\n");
      out.write("                    <p class=\"text-muted\">(Chief Doctor)</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-3 col-sm-6\">\r\n");
      out.write("                <div class=\"card paint-card text-center p-2\">\r\n");
      out.write("                    <img src=\"img/doctor1.avif\" class=\"team-img\" width=\"100%\">\r\n");
      out.write("                    <h5 class=\"fw-bold mt-2\">Dr. Satish Yadav</h5>\r\n");
      out.write("                    <p class=\"text-muted\">(Chief Doctor)</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("<div class=\"container-fluid p-2 text-center text-white\" style=\"background-color:#2C3E50;\">\r\n");
      out.write("    <p>&copy; 2025 Hospital Management System | All Rights Reserved</p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
