/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.108
 * Generated at: 2025-08-23 16:41:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.entity.Doctor;
import java.util.List;
import com.db.DBConnect;
import com.dao.DoctorDao;

public final class user_005fappointment_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/component/navbar.jsp", Long.valueOf(1755622599510L));
    _jspx_dependants.put("/component/css.jsp", Long.valueOf(1753599776025L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.dao.DoctorDao");
    _jspx_imports_classes.add("com.db.DBConnect");
    _jspx_imports_classes.add("com.entity.Doctor");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>User Appointment</title>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.0/css/all.min.css\"\r\n");
      out.write("	integrity=\"sha512-DxV+EoADOkOygM4IR9yXP8Sb2qwgidEmeqAEmDKIOfPRQZOWbXCzLC6vjbZyy0vPisbH2SyW27+ddLVCN+OMzQ==\"\r\n");
      out.write("	crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("		integrity=\"sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM\"\r\n");
      out.write("		crossorigin=\"anonymous\"></script>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".paint-card {\r\n");
      out.write("	box-shadow: 0 0 8px 0 rgba(0, 0, 0, 0.3);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".backImg {\r\n");
      out.write("	background: linear-gradient(rgba(0, 0, 0, .4), rgba(0, 0, 0, .4)),\r\n");
      out.write("		url(\"img/22.jpg\");\r\n");
      out.write("	height: 20vh;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	background-size: cover;\r\n");
      out.write("	background-repeat: no-repeat;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".custom-btn {\r\n");
      out.write("	background-color: #2C3E50; /* Button color */\r\n");
      out.write("	color: white; /* Text color */\r\n");
      out.write("	border: none; /* Optional: removes border */\r\n");
      out.write("	padding: 10px; /* Adds some spacing */\r\n");
      out.write("	border-radius: 8px; /* Rounded corners */\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("/* Navbar background */\r\n");
      out.write(".navbar-custom {\r\n");
      out.write("    background: linear-gradient(90deg, #2C3E50, #34495E);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Nav links */\r\n");
      out.write(".navbar-nav .nav-link {\r\n");
      out.write("    color: white !important;\r\n");
      out.write("    font-weight: 500;\r\n");
      out.write("    margin-right: 14px;\r\n");
      out.write("    transition: 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write(".navbar-nav .nav-link:hover {\r\n");
      out.write("    color: #f39c12 !important; /* Gold hover */\r\n");
      out.write("    transform: translateY(-2px);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Custom dropdown button */\r\n");
      out.write(".custom-btn {\r\n");
      out.write("    background-color: #f39c12; /* Gold */\r\n");
      out.write("    color: white;\r\n");
      out.write("    border: none;\r\n");
      out.write("    border-radius: 8px;\r\n");
      out.write("    padding: 6px 14px;\r\n");
      out.write("    transition: 0.3s;\r\n");
      out.write("}\r\n");
      out.write(".custom-btn:hover {\r\n");
      out.write("    background-color: #d68910;\r\n");
      out.write("    transform: scale(1.05);\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark navbar-custom shadow-sm\">\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- Brand -->\r\n");
      out.write("    <a class=\"navbar-brand fw-bold\" href=\"index.jsp\">\r\n");
      out.write("      <i class=\"fa-solid fa-house-medical\"></i> MEDI HOME\r\n");
      out.write("    </a>\r\n");
      out.write("\r\n");
      out.write("    <!-- Mobile Toggler -->\r\n");
      out.write("    <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" \r\n");
      out.write("            data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" \r\n");
      out.write("            aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("      <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("    </button>\r\n");
      out.write("\r\n");
      out.write("    <!-- Navbar Links -->\r\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("      <ul class=\"navbar-nav ms-auto mb-2 mb-lg-0\">\r\n");
      out.write("\r\n");
      out.write("        ");
 
           Object userObj = session.getAttribute("userObj");
           if (userObj == null) { 
        
      out.write("\r\n");
      out.write("            <!-- Not logged in -->\r\n");
      out.write("            <li class=\"nav-item\"><a class=\"nav-link\" href=\"admin_login.jsp\"><i class=\"fa-solid fa-user-shield\"></i> Admin</a></li>\r\n");
      out.write("            <li class=\"nav-item\"><a class=\"nav-link\" href=\"doctor_login.jsp\"><i class=\"fa-solid fa-stethoscope\"></i> Doctor</a></li>\r\n");
      out.write("            <li class=\"nav-item\"><a class=\"nav-link\" href=\"user_appointment.jsp\"><i class=\"fa-solid fa-calendar-check\"></i> Appointment</a></li>\r\n");
      out.write("            <li class=\"nav-item\"><a class=\"nav-link\" href=\"user_login.jsp\"><i class=\"fa-solid fa-user\"></i> User</a></li>\r\n");
      out.write("\r\n");
      out.write("        ");
 
           } else { 
        
      out.write("\r\n");
      out.write("            <!-- Logged in user -->\r\n");
      out.write("            <li class=\"nav-item\"><a class=\"nav-link\" href=\"user_appointment.jsp\"><i class=\"fa-solid fa-calendar-check\"></i> Appointment</a></li>\r\n");
      out.write("            <li class=\"nav-item\"><a class=\"nav-link\" href=\"view_appointment.jsp\"><i class=\"fa-solid fa-eye\"></i> View Appointment</a></li>\r\n");
      out.write("\r\n");
      out.write("            <!-- User dropdown -->\r\n");
      out.write("            <div class=\"dropdown\">\r\n");
      out.write("              <button class=\"btn custom-btn dropdown-toggle\" type=\"button\" \r\n");
      out.write("                      id=\"dropdownMenuButton1\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("                <i class=\"fas fa-user-circle\"></i> \r\n");
      out.write("                ");
      out.print( ((com.entity.User)userObj).getFullname() );
      out.write("\r\n");
      out.write("              </button>\r\n");
      out.write("              <ul class=\"dropdown-menu dropdown-menu-end shadow\">\r\n");
      out.write("                <li><a class=\"dropdown-item\" href=\"changepassword.jsp\"><i class=\"fa-solid fa-key\"></i> Change Password</a></li>\r\n");
      out.write("                <li><a class=\"dropdown-item\" href=\"userLogout\"><i class=\"fa-solid fa-right-from-bracket\"></i> Logout</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        ");
 
           } 
        
      out.write("\r\n");
      out.write("\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"container-fluid backImg p-5\">\r\n");
      out.write("		<p class=\"text-center fs-2 text-white\"></p>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"container p-3\">\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"col-md-6 p-5\">\r\n");
      out.write("				<img alt=\"\" src=\"img/hos3.jpg\" height=\"500px\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col-md-6 p-5\">\r\n");
      out.write("\r\n");
      out.write("				<div class=\"card paint-card\">\r\n");
      out.write("					<div class=\"card-body\">\r\n");
      out.write("\r\n");
      out.write("						<p class=\"text-center fs-3\">User Appointment</p>\r\n");
      out.write("						<c:if test=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty errorMsg }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("							<p class=\"text-center text-danger fs-4\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${errorMsg }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("							<c:remove var=\"errorMsg\" scope=\"session\" />\r\n");
      out.write("						</c:if>\r\n");
      out.write("						<c:if test=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty succMsg }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("							<p class=\"text-center text-success fs-4\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${succMsg }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("							<c:remove var=\"succMsg\" scope=\"session\" />\r\n");
      out.write("						</c:if>\r\n");
      out.write("						<form class=\"row g-3\" action=\"addAppointment\" method=\"post\">\r\n");
      out.write("							<input type=\"hidden\" name=\"userid\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userObj.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("							<div class=\"col-md-6\">\r\n");
      out.write("								<label for=\"inputEmail4\" class=\"form-label\">Full Name</label><input\r\n");
      out.write("									required type=\"text\" class=\"form-control\" name=\"fullname\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-md-6\">\r\n");
      out.write("								<label for=\"gender\" class=\"form-label\">Gender</label> <select\r\n");
      out.write("									class=\"form-control\" name=\"gender\" id=\"gender\" required>\r\n");
      out.write("									<option value=\"\" disabled selected>Select Gender</option>\r\n");
      out.write("									<option value=\"male\">Male</option>\r\n");
      out.write("									<option value=\"female\">Female</option>\r\n");
      out.write("								</select>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-md-6\">\r\n");
      out.write("								<label for=\"inputEmail4\" class=\"form-label\">Age</label><input\r\n");
      out.write("									required type=\"number\" class=\"form-control\" name=\"age\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-md-6\">\r\n");
      out.write("								<label for=\"inputEmail4\" class=\"form-label\">Appointment\r\n");
      out.write("									Date</label><input type=\"date\" class=\"form-control\" required\r\n");
      out.write("									name=\"appoint_date\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-md-6\">\r\n");
      out.write("								<label for=\"inputEmail4\" class=\"form-label\">Email</label><input\r\n");
      out.write("									required type=\"email\" class=\"form-control\" name=\"email\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-md-6\">\r\n");
      out.write("								<label for=\"inputEmail4\" class=\"form-label\">Phone No</label><input\r\n");
      out.write("									maxlength=\"10\" required type=\"number\" class=\"form-control\"\r\n");
      out.write("									name=\"phno\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-md-6\">\r\n");
      out.write("								<label for=\"inputEmail4\" class=\"form-label\">Diseases</label><input\r\n");
      out.write("									required type=\"text\" class=\"form-control\" name=\"diseases\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-md-6\">\r\n");
      out.write("								<label for=\"inputPassword4\" class=\"form-label\">Doctor</label><select\r\n");
      out.write("									required class=\"form-control\" name=\"doct\">\r\n");
      out.write("									<option value=\"\">--select--</option>\r\n");
      out.write("									");

									DoctorDao dao = new DoctorDao(DBConnect.getConn());
									List<Doctor> list = dao.getAlldoctor();
									for (Doctor d : list) {
									
      out.write("\r\n");
      out.write("									<option value=\"");
      out.print(d.getId());
      out.write('"');
      out.write('>');
      out.print(d.getFullname());
      out.write(' ');
      out.write('(');
      out.print(d.getSpecialist());
      out.write(")\r\n");
      out.write("									</option>\r\n");
      out.write("									");

									}
									
      out.write("\r\n");
      out.write("								</select>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-md-12\">\r\n");
      out.write("								<label>Full Address</label>\r\n");
      out.write("								<textarea required name=\"address\" class=\"form-control\" rows=\"3\"\r\n");
      out.write("									cols=\"\"></textarea>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<c:if test=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ empty userObj }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("								<a href=\"user_login.jsp\"\r\n");
      out.write("									class=\"col-md-6 offset-md-3 btn btn-success\">Submit</a>\r\n");
      out.write("							</c:if>\r\n");
      out.write("							\r\n");
      out.write("						</form>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
